#!/bin/bash

# Create GVL low-privilege, default user

username=researcher

echo "\n** Creating a non-sudo account for user "$username
if [ $(getent passwd $username | wc -l) = '0' ]; then
  # User does not exist yet
  echo "Creating account for "$username
  sudo adduser --disabled-password --gecos "" $username --home "/mnt/gvl/home/"$username
  sudo ln -s "/mnt/gvl/home/"$username "/home/"$username
else
  echo "User "$username" already exists, not creating."
fi

echo "Setting password for "$username
# get salted+hashed password for ubuntu user
ubuntu_password=`sudo getent shadow | grep ubuntu: | awk -F":" '{ print $2 }'`
# replace new user's password with ubuntu user's password
echo $username:$ubuntu_password | sudo chpasswd -e

# Add symlink to genomes directory on CloudMan instances
echo "\n** Creating a symlink to Galaxy reference genomes for "$username
sudo su $username -c 'if [ ! -d ~/galaxy_genomes ]; then ln -s /mnt/galaxyIndices/genomes ~/galaxy_genomes; fi'

# Add symlink to galaxy app directory on CloudMan instances
echo "\n** Creating a symlink to Galaxy for "$username
sudo su $username -c 'if [ ! -d ~/galaxy ]; then ln -s /mnt/galaxy/galaxy-app ~/galaxy; fi'